repos:
- hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
  repo: meta
- hooks:
  - id: trailing-whitespace
    exclude: .*\.obsidian/.*
  - id: end-of-file-fixer
    exclude: .*\.obsidian/.*
  - files: ^\.pre-commit-config\.yaml$
    id: check-yaml
    name: Check pre-commit config
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - description: Scan Nix files for dead code
    id: deadnix
    name: deadnix
    entry: deadnix --edit --fail # --no-lambda-arg --no-lambda-pattern-names
    language: system
    files: \.nix$
  - description: Format nix code with nixpkgs-fmt.
    id: nixpkgs-fmt
    name: nixpkgs-fmt
    entry: nixpkgs-fmt
    language: system
    files: \.nix$
  repo: local
